services:
    anime_db.anime_news_network.browser:
        class: AnimeDb\Bundle\AnimeNewsNetworkBrowserBundle\Service\Browser
        arguments: [ '@anime_db.anime_news_network.browser.client', ~, ~, ~, ~ ]

    anime_db.anime_news_network.browser.client:
        class: GuzzleHttp\Client
        public: false
